#!/usr/bin/env php
<?php

set_time_limit(0);

require __DIR__ . '/../vendor/autoload.php';
require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;

$input = new ArgvInput();
$debug = true;

if ($debug) {
    Debug::enable();
}

$kernel = new AppKernel('dev', $debug);
$application = new Application($kernel);
$application->run($input);
