services:
    broadway_demo.controller.basket:
        class: BroadwayDemo\Controller\BasketController
        arguments:
            - '@broadway.command_handling.command_bus'
            - '@broadway.uuid.generator'
        public: true

    broadway_demo.controller.people_that_bought_this_product:
        class: BroadwayDemo\Controller\PeopleThatBoughtThisProductAlsoBoughtController
        arguments:
            - '@broadway_demo.read_model.repository.people_that_bought_this_product'
        public: true

    broadway.stack.request_id.monolog_processor:
        class: Qandidate\Stack\RequestId\MonologProcessor
        tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 255 }
        - { name: monolog.processor }

    broadway_demo.command.create_read_model:
        class: BroadwayDemo\Command\CreateReadModelCommand
        tags:
        - { name: console.command }

    broadway_demo.command.drop_read_model:
        class: BroadwayDemo\Command\DropReadModelCommand
        tags:
        - { name: console.command }
